name: "Feature"
description: "Request a new feature"
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: One sentence summary
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What problem does this solve? Any constraints?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "Given/When/Then…"
