name: "Hotfix"
description: "Urgent fix needed"
labels: ["hotfix"]
body:
  - type: input
    id: impact
    attributes:
      label: Impact
      placeholder: e.g. production user-facing, data loss risk, etc.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Repro / Context
  - type: textarea
    id: scope
    attributes:
      label: Scope / Constraints
