name: Change / Release Request
description: Basic change request form.
title: "[Change]"
labels:
  - change-request
body:
  # ─────────────── Details (type-into fields) ───────────────
  - type: markdown
    attributes:
      value: "## Details"

  - type: input
    id: start_date
    attributes:
      label: Start date
    validations:
      required: true

  - type: input
    id: end_date
    attributes:
      label: End date
    validations:
      required: true

  - type: input
    id: effort_project
    attributes:
      label: Effort / Project
    validations:
      required: true

  # ─────────────── Rationale ───────────────
  - type: markdown
    attributes:
      value: "## Rationale"

  - type: textarea
    id: justification
    attributes:
      label: Justification
    validations:
      required: true

  - type: textarea
    id: implementation_plan
    attributes:
      label: Implementation plan
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Risk
    validations:
      required: true

  # ─────────────── Audience & Contacts ───────────────
  - type: markdown
    attributes:
      value: "## Audience & Contacts"

  - type: input
    id: impacted_groups
    attributes:
      label: Impacted groups
    validations:
      required: true

  - type: input
    id: impacted_users_emails
    attributes:
      label: Impacted users (emails)
    validations:
      required: true

  - type: input
    id: last_notified_when
    attributes:
      label: When were impacted users last notified?
    validations:
      required: true

  # ─────────────── Dropdowns ───────────────
  - type: markdown
    attributes:
      value: "## Communication"

  - type: dropdown
    id: last_notified_how
    attributes:
      label: How were impacted users last notified?
      options:
        - Meeting
        - Teams message
        - Email
    validations:
      required: true

  - type: input
    id: backup_contact
    attributes:
      label: Backup contact (email)
    validations:
      required: true

  # ─────────────── Bottom: Checkboxes (confirmations + toggles) ───────────────
  - type: markdown
    attributes:
      value: "## Confirmations & Flags"

  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmations
      description: Please confirm the following by checking the boxes.
      options:
        - label: I have searched the existing issues and this is not a duplicate.
          required: true
        - label: I'd like to work on this issue myself.
          required: false
        - label: Impacts the public.
          required: false
        - label: Involves CDT.
          required: false
        - label: New app (ESD needs to know).
          required: false
