name: Pipeline Caller

on:
  push:
    branches: [ "feature/**" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [ready_for_review, closed]



permissions:
  write-all

jobs:

  pre-check:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.check.outputs.target_env }}
      sha:   ${{ steps.check.outputs.sha }}
      rc_tag:     ${{ steps.check.outputs.rc_tag }}
      pr_num:  ${{ steps.check.outputs.pr_num }}
    steps:
      - name: set target_env and decide skip
        id: check
        uses: dhillon-shawn/Local-Uipath-CICD/.github/actions/pre-check@main


  stage:
    needs: pre-check
    if: needs.pre-check.outputs.target_env != '' && needs.pre-check.outputs.target_env != 'prod'
    uses: dhillon-shawn/Local-Uipath-CICD/.github/workflows/pipeline.yml@main
    secrets: inherit
    with:
      target_env: ${{ needs.pre-check.outputs.target_env }}
      sha:        ${{ needs.pre-check.outputs.sha }}
      rc_tag:     ${{ needs.pre-check.outputs.rc_tag }}
      pr_num:     ${{ needs.pre-check.outputs.pr_num }}

  rc-promotion:
    needs: pre-check
    if: needs.pre-check.outputs.target_env == 'prod'
    uses: dhillon-shawn/Local-Uipath-CICD/.github/workflows/promote-rc.yml@main
    secrets: inherit
    with:
      rc_tag: ${{ needs.pre-check.outputs.rc_tag }}
      pr_num: ${{ needs.pre-check.outputs.pr_num }}
