# .github/workflows/closing-pr-on-reopen.yml
name: Find last closing PR when issue reopens

on:
  issues:
    types: [reopened]

permissions:
  issues: read
  pull-requests: read
  contents: read

jobs:
  find-last-closing-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR that last closed this issue
        id: find
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;

            let page = 1, last = null;
            while (true) {
              const res = await github.request(
                'GET /repos/{owner}/{repo}/issues/{issue_number}/timeline',
                { owner, repo, issue_number, per_page: 100, page }
              );

              for (const e of res.data) {
                // Look for PRs that referenced this issue with "will close" semantics (e.g. "fixes #123")
                if (e.event === 'cross-referenced' && e.will_close && e.source?.issue?.pull_request) {
                  const prNum = e.source.issue.number;
                  const pr = await github.rest.pulls.get({ owner, repo, pull_number: prNum });
                  if (pr.data.merged_at) {
                    if (!last || new Date(pr.data.merged_at) > new Date(last.merged_at)) {
                      last = { number: pr.data.number, merged_at: pr.data.merged_at };
                    }
                  }
                }
              }

              if (res.data.length < 100) break;
              page++;
            }

            if (!last) {
              core.setFailed('No merged PR found that closed this issue.');
              return;
            }
            return String(last.number);

      - name: Use it
        run: echo "Last closing PR number ${{ steps.find.outputs.result }}"
