# .github/workflows/get-pr-on-reopen.yml
name: Get PR number on issue reopen
on:
  issues:
    types: [reopened]

permissions:
  issues: read

jobs:
  get-pr:
    runs-on: ubuntu-latest
    steps:
      - id: find
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const {owner, repo} = context.repo;
            const issue_number = context.payload.issue.number;
            const re = /https?:\/\/github\.com\/[^/]+\/[^/]+\/pull\/(\d+)/;

            let page = 1, pr = null;
            while (!pr) {
              const {data} = await github.rest.issues.listComments({
                owner, repo, issue_number, per_page: 100, page,
                sort: 'created', direction: 'desc'
              });
              for (const c of data) { const m = re.exec(c.body || ''); if (m) { pr = m[1]; break; } }
              if (data.length < 100) break; page++;
            }
            if (!pr) { core.setFailed('No PR URL found in comments.'); return; }
            core.setOutput('pr_number', pr); return pr;

      - name: Use it
        run: echo "PR number #${{ steps.find.outputs.result }}"
